include("baseline.jl")
using .Baseline, Test

@testset "trivial, single matches" begin
    @test match("0", ["0"]) == "1"
    @test match("0", ["1"]) == "0"
    @test match("10", ["1"]) == "1"
    @test match("11", ["1"]) == "1"
    @test match("11", ["0"]) == "0"
    @test match("10", ["0"]) == "1"
    @test match("10111", ["0"]) == "1"
end

@testset "matching multiple single-char strings" begin
    @test match("10001", ["0", "1", "3"]) == "110"
    @test match("0155555592", ["0", "1", "9", "2"]) == "1111"
    @test match("0155555592", ["7", "5", "3", "1"]) == "0101"
end

@testset "matching multiple short intersecting strings" begin
    strings = ["123", "12345"]
    @test match("12345", strings) == "11"

    strings = ["123", "12345", "234"]
    @test match("12345", strings) == "111"

    strings = ["123", "12345", "23"]
    @test match("12345", strings) == "111"
end

@testset "intersections within intersections" begin
    @test match("12345", ["234", "3"]) == "11"

    matches = match("1234567890", ["12345", "567890", "123", "890", "9"])
    @test matches == "11111"

    matches = match("1234567890", ["12345", "567890", "123", "890", "345", "23", "12"])
    @test matches == "1111111"

    matches = match("1234567890", ["2345678", "34567", "456", "5"])
    @test matches == "1111"

end

@testset "find some intersects" begin
    to_match = ["GACTG", "ACT", "ACGACTGAGCACT"]

    matches = match("ATGTTGGACACTCGGCGGACGACTGAGCACTGGAACTTTTTAAA", to_match)
    @test matches == "111"
end

function bulktest(source::String, strings::Vector{String}, match_result::String)
    @test match(source, strings) == match_result
end

@testset "matching many little strings" begin
    bulktest("ATGTTGGACACTCGGCGGACGACTGAGCACTGGAACTTTTTAAA", ["ACGACTGAGCACT", "GAC", "ACG", "ACGACT", "ACT"], "11111")
    bulktest("GGCTCAAATTACACGTAAACTTAAGAATATTCG", ["TAC", "ACA", "TTACA", "ATA", "TAT", "ATAT"] , "111111")
    bulktest("CAGTCATAAAATACATTCAAGTATCAATAAATAG", ["CAGTCATAA", "AGT", "CAT", "GTCAT"], "1111")
    bulktest("ACGACTGAGCACT", ["GACTG", "ACT"], "11")
    bulktest("ATGTTGGACACTCGGCGGACGACTGAGCACTGGAACTTTTTAAA", ["ACT", "ACGACTGAGCACT", "GACTG"], "111")
    bulktest("CACCCACAATCAGGCGAAGAGCCCCGAC", ["CAC", "GAG", "GCC"], "111")
    bulktest("1111111111", ["1", "11", "111", "1111", "11111", "111111"], "111111")
end

@testset "small and big string on a moderate size source" begin
    source = open("./data/drosophila.fasta") do file
        read(file, String)
    end

    string = "ATGTTGGAACCGGCGGGGAACTTTTTAAATTTTAATGGCTTCAGCGAACCCGAAAAAGCACTCGAGGGTGCCATCATAAGAGAGATTGAAGATGGAGTTCGCTGTGAGCAATGTAAATCAGATTGCCCGGGTTTTGCAGCTCACGATTGGAGGAAAACCTGCCAATCCTGCAAATGTCCTCGCGAGGCACATGCCATATACCAGCAACAAACGACCAACGTCCACGAGCGACTCGGCTTCAAACTGGTTTCCCCGGCGGATTCCGGAGTGGAGGCGAGGGATCTGGGCTTCACGTGGGTTCCGCCCGGACTGCGAGCCTCGTCGCGGATCATCCGCTATTTCGAGCAGCTGCCCGATGAGGCGGTGCCCCGGTTGGGCAGCGAGGGAGCCTGCAGTCGGGAGCGCCAGATCTCGTACCAGCTGCCCAAACAGGACCTCTCGCTGGAGCACTGTAAGCACCTGGAGGTGCAGCACGAGTCCTCCTTCGAGGACTTTGTGACGGCGCGGAACGAAATCGCACTGGATATAGCCTACATCAAGGATGCACCCTACGATGAGCATTGTGCGCACTGTGATAACGAGATAGCTGCCGGCGAGCTGGTTGTAGCGGCGCCCAAGTTTGTGGAGAGCGTGATGTGGCACCCCAAGTGCTTCACCTGCAGCACCTGCAACCTGCTCCTGGTGGACCTCACCTACTGTGTCCACGACGACAAGGTCTACTGCGAGCGCCACTATGCGGAAATGCTGAAGCCCCGCTGCGCTGGCTGTGATGAGGTGAGTTCCCTCTAG"

    @time matches = match(source, ["TAAAAAACGT", string])
    @test matches == "11"
end


@testset "match three big intersecting strings" begin
    source = open("./data/drosophila.fasta") do file
        read(file, String)
    end

    strings = ["ATGTTGGAACCGGCGGGGAACTTTTTAAATTTTAATGGCTTCAGCGAACCCGAAAAAGCACTCGAGGGTGCCATCATAAGAGAGATTGAAGATGGAGTTCGCTGTGAGCAATGTAAATCAGATTGCCCGGGTTTTGCAGCTCACGATTGGAGGAAAACCTGCCAATCCTGCAAATGTCCTCGCGAGGCACATGCCATATACCAGCAACAAACGACCAACGTCCACGAGCGACTCGGCTTCAAACTGGTTTCCCCGGCGGATTCCGGAGTGGAGGCGAGGGATCTGGG",
               "ATGTTGGAACCGGCGGGGAACTTTTTAAATTTTAATGGCTTCAGCGAACCCGAAAAAGCACTCGAGGGTGCCATCATAAGAGAGATTGAAGATGGAGTTCGCTGTGAGCAATGTAAATCAGATTGCCCGGGTTTTGCAGCTCACGATTGGAGGAAAACCTGCCAATCCTGCAAATGTCCTCGCGAGGCACATGCCATATACCAGCAACAAACGACCAACGTCCACGAGCGACTCGGCTTCAAACTGGTTTCCCCGGCGGATTCCGGAGTGGAGGCGAGGGATCTGGGCTTCACGTGGGTTCCGCCCGGACTGCGAGCCTCGTCGCGGATCATCCGCTATTTCGAGCAGCTGCCCGATGAGGCGGTGCCCCGGTTGGGCAGCGAGGGAGCCTGCAGTCGGGAGCGCCAGATCTCGTACCAGCTGCCCAAACAGGACCTCTCGCTGGAGCACTGTAAGCACCTGGAGGTGCAGCACGAGTCCTCCTTCGAGGACTTTGTGACGGCGCGGAACGAAATCGCACTGGATATAGCCTACATCAAGGATGCACCCTACGATGAGCATTGTGCGCACTGTGATAACGAGATAGCTGCCGGCGAGCTGGTTGTAGCGGCGCCCAAGTTTGTGGAGAGCGTGATGTGGCACCCCAAGTGCTTCACCTGCAGCACCTGCAACCTGCTCCTGGTGGACCTCACCTACTGTGTCCACGACGACAAGGTCTACTGCGAGCGCCACTATGCGGAAATGCTGAAGCCCCGCTGCGCTGGCTGTGATGAGGTGAGTTCCCTCTAG",
               "AATGGCTTCAGCGAACCCGAAAAAGCACTCGAGGGTGCCATCATAAGAGAGATTGAAGATGGAGTTCGCTGTGAGCAATGTAAATCAGATTGCCCGG"]

    @time matches = match(source, strings)
    @test matches == "111"
end

@testset "benchmark 2000 markers" begin
    @time match("./data/thaliana.fna", "./data/2000markers.csv", "result.txt")
end
